image: node:20-slim

before_script:
  - corepack enable && corepack prepare pnpm@latest --activate

stages:
  - lint
  - build

lint_project:
  stage: lint
  script:
    - pnpm install --no-frozen-lockfile
    - pnpm lint --no-fix --max-warnings=0

build_project:
  stage: build
  script:
    - pnpm install --no-frozen-lockfile
    - pnpm build
