image: node:20-slim

cache:
  paths:
    - node_modules/
    - /root/.local/share/pnpm

before_script:
  - corepack enable && corepack prepare pnpm@latest --activate

stages:
  - install
  - lint
  - build

install_dependencies:
  stage: install
  script:
    - pnpm install

lint_project:
  stage: lint
  script:
    - pnpm lint --no-fix

build_project:
  stage: build
  script:
    - pnpm build
